import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./layout/Navbar";
import Balls from "./components/reusable components/Balls";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className, "bg-black w-screen max-w-full font-Montserrat ")
        }
      >
        <div className="max-w-[1440px] mx-auto ">
          <Navbar />

          {children}
        </div>
      </body>
    </html>
  );
}
