import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./layout/Navbar";
import Balls from "./components/reusable components/Balls";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";
import favicon from "@/public/favicon.ico";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gabriel Ibanez Portfolio",
  description: "Generated by create next app",
  icons: favicon.src,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className, "bg-black w-screen max-w-full font-Montserrat ")
        }
      >
        <div className="max-w-[1440px] mx-auto ">
          <Navbar />
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
